env:
  browser: true
  node: true
  es6: true
  jest: true
root: true
extends:
  - airbnb
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - '@typescript-eslint'
globals:
  GIT_INFO: false
rules:
  arrow-parens: [error, always]
  arrow-spacing: error
  comma-spacing: error
  comma-style: error
  eol-last: error
  import/extensions: off
  import/no-named-as-default-member: off
  import/no-extraneous-dependencies: off
  import/no-unresolved: off
  import/no-webpack-loader-syntax: off
  import/prefer-default-export: off
  indent: [error, 2, {SwitchCase: 1}]
  keyword-spacing: error
  linebreak-style: [error, unix]
  no-console: error
  no-constant-condition: off
  no-param-reassign: [error, {props: false}]
  no-tabs: error
  no-trailing-spaces: error
  '@typescript-eslint/no-unused-vars': [error, {argsIgnorePattern: "^_"}]
  no-var: error
  prefer-const: error
  quotes: [error, double, {avoidEscape: true}]
  rest-spread-spacing: error
  semi-spacing: error
  semi: [error, always]
  space-before-blocks: error
  space-infix-ops: error
