env:
  browser: true
  es6: true
  jest: true
extends:
  - "airbnb"
  - "eslint:recommended"
  - "plugin:react/recommended"
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
globals:
  GIT_INFO: false
rules:
  arrow-parens: [error, always]
  arrow-spacing: error
  comma-dangle:
    - error
    - arrays: always-multiline
      exports: always-multiline
      functions: never
      imports: always-multiline
      objects: always-multiline
  comma-spacing: error
  comma-style: error
  eol-last: error
  import/extensions: off
  import/no-extraneous-dependencies: off
  import/no-unresolved: off
  import/no-webpack-loader-syntax: off
  import/prefer-default-export: off
  indent: [error, 2, {SwitchCase: 1}]
  jsx-a11y/anchor-is-valid: off
  jsx-a11y/click-events-have-key-events: off
  jsx-a11y/no-noninteractive-tabindex: off
  jsx-a11y/no-static-element-interactions: off
  jsx-a11y/label-has-for: off
  jsx-quotes: [error, prefer-double]
  keyword-spacing: error
  linebreak-style: [error, unix]
  no-console: error
  no-constant-condition: off
  no-param-reassign: [error, {props: false}]
  no-tabs: error
  no-trailing-spaces: error
  no-unused-vars: [error]
  no-var: error
  prefer-const: error
  quotes: [error, double]
  react/default-props-match-prop-types: off # https://github.com/yannickcr/eslint-plugin-react/issues/1468
  react/jsx-closing-tag-location: off
  react/jsx-closing-bracket-location: [error, {selfClosing: line-aligned, nonEmpty: after-props}]
  react/jsx-filename-extension: off
  react/jsx-no-bind: off
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
  react/jsx-wrap-multilines: off
  react/no-array-index-key: off
  react/no-multi-comp: off
  react/prefer-stateless-function: off
  react/prop-types: off
  react/require-default-props: off
  react/sort-comp: off
  rest-spread-spacing: error
  semi-spacing: error
  semi: [error, always]
  space-before-blocks: error
  space-infix-ops: error
