// flow-typed signature: 62a5f40d8fc5bd57421633bb188fd7a7
// flow-typed version: <<STUB>>/compressjs_v1.0.3/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'compressjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'compressjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'compressjs/lib/BitStream' {
  declare module.exports: any;
}

declare module 'compressjs/lib/BWT' {
  declare module.exports: any;
}

declare module 'compressjs/lib/BWTC' {
  declare module.exports: any;
}

declare module 'compressjs/lib/Bzip2' {
  declare module.exports: any;
}

declare module 'compressjs/lib/Context1Model' {
  declare module.exports: any;
}

declare module 'compressjs/lib/CRC32' {
  declare module.exports: any;
}

declare module 'compressjs/lib/DeflateDistanceModel' {
  declare module.exports: any;
}

declare module 'compressjs/lib/DefSumModel' {
  declare module.exports: any;
}

declare module 'compressjs/lib/Dmc' {
  declare module.exports: any;
}

declare module 'compressjs/lib/DummyRangeCoder' {
  declare module.exports: any;
}

declare module 'compressjs/lib/FenwickModel' {
  declare module.exports: any;
}

declare module 'compressjs/lib/freeze' {
  declare module.exports: any;
}

declare module 'compressjs/lib/Huffman' {
  declare module.exports: any;
}

declare module 'compressjs/lib/HuffmanAllocator' {
  declare module.exports: any;
}

declare module 'compressjs/lib/LogDistanceModel' {
  declare module.exports: any;
}

declare module 'compressjs/lib/Lzjb' {
  declare module.exports: any;
}

declare module 'compressjs/lib/LzjbR' {
  declare module.exports: any;
}

declare module 'compressjs/lib/Lzp3' {
  declare module.exports: any;
}

declare module 'compressjs/lib/MTFModel' {
  declare module.exports: any;
}

declare module 'compressjs/lib/NoModel' {
  declare module.exports: any;
}

declare module 'compressjs/lib/PPM' {
  declare module.exports: any;
}

declare module 'compressjs/lib/RangeCoder' {
  declare module.exports: any;
}

declare module 'compressjs/lib/Simple' {
  declare module.exports: any;
}

declare module 'compressjs/lib/Stream' {
  declare module.exports: any;
}

declare module 'compressjs/lib/Util' {
  declare module.exports: any;
}

declare module 'compressjs/main' {
  declare module.exports: any;
}

declare module 'compressjs/test/bwtest' {
  declare module.exports: any;
}

declare module 'compressjs/test/bzip2-basic' {
  declare module.exports: any;
}

declare module 'compressjs/test/bzip2-block' {
  declare module.exports: any;
}

declare module 'compressjs/test/bzip2-table' {
  declare module.exports: any;
}

declare module 'compressjs/test/file' {
  declare module.exports: any;
}

declare module 'compressjs/test/huffman' {
  declare module.exports: any;
}

declare module 'compressjs/test/range' {
  declare module.exports: any;
}

declare module 'compressjs/test/suftest' {
  declare module.exports: any;
}

declare module 'compressjs/test/test-fls' {
  declare module.exports: any;
}

// Filename aliases
declare module 'compressjs/lib/BitStream.js' {
  declare module.exports: $Exports<'compressjs/lib/BitStream'>;
}
declare module 'compressjs/lib/BWT.js' {
  declare module.exports: $Exports<'compressjs/lib/BWT'>;
}
declare module 'compressjs/lib/BWTC.js' {
  declare module.exports: $Exports<'compressjs/lib/BWTC'>;
}
declare module 'compressjs/lib/Bzip2.js' {
  declare module.exports: $Exports<'compressjs/lib/Bzip2'>;
}
declare module 'compressjs/lib/Context1Model.js' {
  declare module.exports: $Exports<'compressjs/lib/Context1Model'>;
}
declare module 'compressjs/lib/CRC32.js' {
  declare module.exports: $Exports<'compressjs/lib/CRC32'>;
}
declare module 'compressjs/lib/DeflateDistanceModel.js' {
  declare module.exports: $Exports<'compressjs/lib/DeflateDistanceModel'>;
}
declare module 'compressjs/lib/DefSumModel.js' {
  declare module.exports: $Exports<'compressjs/lib/DefSumModel'>;
}
declare module 'compressjs/lib/Dmc.js' {
  declare module.exports: $Exports<'compressjs/lib/Dmc'>;
}
declare module 'compressjs/lib/DummyRangeCoder.js' {
  declare module.exports: $Exports<'compressjs/lib/DummyRangeCoder'>;
}
declare module 'compressjs/lib/FenwickModel.js' {
  declare module.exports: $Exports<'compressjs/lib/FenwickModel'>;
}
declare module 'compressjs/lib/freeze.js' {
  declare module.exports: $Exports<'compressjs/lib/freeze'>;
}
declare module 'compressjs/lib/Huffman.js' {
  declare module.exports: $Exports<'compressjs/lib/Huffman'>;
}
declare module 'compressjs/lib/HuffmanAllocator.js' {
  declare module.exports: $Exports<'compressjs/lib/HuffmanAllocator'>;
}
declare module 'compressjs/lib/LogDistanceModel.js' {
  declare module.exports: $Exports<'compressjs/lib/LogDistanceModel'>;
}
declare module 'compressjs/lib/Lzjb.js' {
  declare module.exports: $Exports<'compressjs/lib/Lzjb'>;
}
declare module 'compressjs/lib/LzjbR.js' {
  declare module.exports: $Exports<'compressjs/lib/LzjbR'>;
}
declare module 'compressjs/lib/Lzp3.js' {
  declare module.exports: $Exports<'compressjs/lib/Lzp3'>;
}
declare module 'compressjs/lib/MTFModel.js' {
  declare module.exports: $Exports<'compressjs/lib/MTFModel'>;
}
declare module 'compressjs/lib/NoModel.js' {
  declare module.exports: $Exports<'compressjs/lib/NoModel'>;
}
declare module 'compressjs/lib/PPM.js' {
  declare module.exports: $Exports<'compressjs/lib/PPM'>;
}
declare module 'compressjs/lib/RangeCoder.js' {
  declare module.exports: $Exports<'compressjs/lib/RangeCoder'>;
}
declare module 'compressjs/lib/Simple.js' {
  declare module.exports: $Exports<'compressjs/lib/Simple'>;
}
declare module 'compressjs/lib/Stream.js' {
  declare module.exports: $Exports<'compressjs/lib/Stream'>;
}
declare module 'compressjs/lib/Util.js' {
  declare module.exports: $Exports<'compressjs/lib/Util'>;
}
declare module 'compressjs/main.js' {
  declare module.exports: $Exports<'compressjs/main'>;
}
declare module 'compressjs/test/bwtest.js' {
  declare module.exports: $Exports<'compressjs/test/bwtest'>;
}
declare module 'compressjs/test/bzip2-basic.js' {
  declare module.exports: $Exports<'compressjs/test/bzip2-basic'>;
}
declare module 'compressjs/test/bzip2-block.js' {
  declare module.exports: $Exports<'compressjs/test/bzip2-block'>;
}
declare module 'compressjs/test/bzip2-table.js' {
  declare module.exports: $Exports<'compressjs/test/bzip2-table'>;
}
declare module 'compressjs/test/file.js' {
  declare module.exports: $Exports<'compressjs/test/file'>;
}
declare module 'compressjs/test/huffman.js' {
  declare module.exports: $Exports<'compressjs/test/huffman'>;
}
declare module 'compressjs/test/range.js' {
  declare module.exports: $Exports<'compressjs/test/range'>;
}
declare module 'compressjs/test/suftest.js' {
  declare module.exports: $Exports<'compressjs/test/suftest'>;
}
declare module 'compressjs/test/test-fls.js' {
  declare module.exports: $Exports<'compressjs/test/test-fls'>;
}
