// flow-typed signature: 3ab4162f3714b21303ce94c63ccc2ce9
// flow-typed version: <<STUB>>/heap_v0.2.6/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'heap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'heap/lib/heap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'heap/index' {
  declare module.exports: $Exports<'heap'>;
}
declare module 'heap/index.js' {
  declare module.exports: $Exports<'heap'>;
}
declare module 'heap/lib/heap.js' {
  declare module.exports: $Exports<'heap/lib/heap'>;
}
