// flow-typed signature: 0875d658735ef1324160a131714ea1a7
// flow-typed version: <<STUB>>/int53_v0.2.4/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'int53'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'int53' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'int53/index' {
  declare module.exports: $Exports<'int53'>;
}
declare module 'int53/index.js' {
  declare module.exports: $Exports<'int53'>;
}
