// flow-typed signature: fe53eef9a89ab69bcde9f13a61c2b218
// flow-typed version: <<STUB>>/lz4js_v0.2.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lz4js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lz4js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lz4js/lz4' {
  declare module.exports: any;
}

declare module 'lz4js/test/cases/lz4' {
  declare module.exports: any;
}

declare module 'lz4js/test/cases/xxh32' {
  declare module.exports: any;
}

declare module 'lz4js/util' {
  declare module.exports: any;
}

declare module 'lz4js/xxh32' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lz4js/lz4.js' {
  declare module.exports: $Exports<'lz4js/lz4'>;
}
declare module 'lz4js/test/cases/lz4.js' {
  declare module.exports: $Exports<'lz4js/test/cases/lz4'>;
}
declare module 'lz4js/test/cases/xxh32.js' {
  declare module.exports: $Exports<'lz4js/test/cases/xxh32'>;
}
declare module 'lz4js/util.js' {
  declare module.exports: $Exports<'lz4js/util'>;
}
declare module 'lz4js/xxh32.js' {
  declare module.exports: $Exports<'lz4js/xxh32'>;
}
